import {
  UserProfile,
  FinancialAccount,
  Category,
  Transaction,
  Budget,
  FinancialGoal,
  TradingAccount,
  Trade,
  Strategy,
  MarketEvent,
  AIInsight,
} from '@/types';

export const mockUserProfile: UserProfile = {
  id: 'usr_vyno_001',
  display_name: 'Alex Pratama',
  avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  default_currency: 'USD',
  timezone: 'Asia/Jakarta (UTC+7)',
  tier: 'PRO',
};

export const mockFinancialAccounts: FinancialAccount[] = [
  {
    id: 'fa_1',
    user_id: 'usr_vyno_001',
    name: 'BCA Main Checking',
    institution: 'Bank Central Asia',
    account_number: '•••• 8920',
    account_type: 'bank',
    currency: 'IDR',
    initial_balance: 35000000,
    current_balance: 48250000, // ~ $3,015 USD
    is_active: true,
  },
  {
    id: 'fa_2',
    user_id: 'usr_vyno_001',
    name: 'GoPay & OVO E-Wallet',
    institution: 'GoTo Financial',
    account_number: '0812••••441',
    account_type: 'ewallet',
    currency: 'IDR',
    initial_balance: 2000000,
    current_balance: 3650000, // ~ $228 USD
    is_active: true,
  },
  {
    id: 'fa_3',
    user_id: 'usr_vyno_001',
    name: 'High Yield Savings',
    institution: 'Bank Jago',
    account_number: '•••• 1109',
    account_type: 'savings',
    currency: 'IDR',
    initial_balance: 80000000,
    current_balance: 115000000, // ~ $7,187 USD
    is_active: true,
  },
  {
    id: 'fa_4',
    user_id: 'usr_vyno_001',
    name: 'USD Reserve & Crypto',
    institution: 'Wise & Binance',
    account_number: 'alex.p@wise',
    account_type: 'investment',
    currency: 'USD',
    initial_balance: 4000,
    current_balance: 6240,
    is_active: true,
  },
  {
    id: 'fa_5',
    user_id: 'usr_vyno_001',
    name: 'Cash Vault',
    institution: 'Physical Wallet',
    account_type: 'cash',
    currency: 'IDR',
    initial_balance: 1500000,
    current_balance: 1200000, // ~ $75 USD
    is_active: true,
  },
];

export const mockCategories: Category[] = [
  { id: 'cat_salary', name: 'Tech / Consulting Salary', type: 'income', icon: 'Briefcase', color: '#10b981' },
  { id: 'cat_prop_payout', name: 'Trading Payout / Profits', type: 'income', icon: 'TrendingUp', color: '#06b6d4' },
  { id: 'cat_invest_div', name: 'Investments / Yield', type: 'income', icon: 'Coins', color: '#8b5cf6' },
  { id: 'cat_housing', name: 'Housing & Utilities', type: 'expense', icon: 'Home', color: '#f59e0b' },
  { id: 'cat_food', name: 'Food & Groceries', type: 'expense', icon: 'Utensils', color: '#ec4899' },
  { id: 'cat_subscriptions', name: 'Software & Tools', type: 'expense', icon: 'Cpu', color: '#3b82f6' },
  { id: 'cat_trading_cost', name: 'Trading VPS & Data Feed', type: 'expense', icon: 'Activity', color: '#6366f1' },
  { id: 'cat_lifestyle', name: 'Lifestyle & Fitness', type: 'expense', icon: 'Coffee', color: '#14b8a6' },
  { id: 'cat_transport', name: 'Transport & Fuel', type: 'expense', icon: 'Car', color: '#64748b' },
];

export const mockTransactions: Transaction[] = [
  {
    id: 'tx_1',
    user_id: 'usr_vyno_001',
    account_id: 'fa_4',
    category_id: 'cat_prop_payout',
    type: 'income',
    amount: 2850,
    currency: 'USD',
    description: 'FTMO Prop Firm Bi-Weekly Profit Split (80%)',
    transaction_date: '2026-09-04T10:00:00Z',
  },
  {
    id: 'fa_tx_2',
    user_id: 'usr_vyno_001',
    account_id: 'fa_1',
    category_id: 'cat_salary',
    type: 'income',
    amount: 32000000,
    currency: 'IDR',
    description: 'Senior Software Engineer Monthly Remuneration',
    transaction_date: '2026-09-01T09:00:00Z',
  },
  {
    id: 'tx_3',
    user_id: 'usr_vyno_001',
    account_id: 'fa_1',
    category_id: 'cat_housing',
    type: 'expense',
    amount: 8500000,
    currency: 'IDR',
    description: 'Apartment Monthly Rent & Maintenance Fee',
    transaction_date: '2026-09-02T14:30:00Z',
  },
  {
    id: 'tx_4',
    user_id: 'usr_vyno_001',
    account_id: 'fa_4',
    category_id: 'cat_subscriptions',
    type: 'expense',
    amount: 79.95,
    currency: 'USD',
    description: 'TradingView Premium + London VPS Server',
    transaction_date: '2026-09-03T18:20:00Z',
  },
  {
    id: 'tx_5',
    user_id: 'usr_vyno_001',
    account_id: 'fa_2',
    category_id: 'cat_food',
    type: 'expense',
    amount: 450000,
    currency: 'IDR',
    description: 'Weekly Organic Grocery Stock & Meal Prep',
    transaction_date: '2026-09-05T11:15:00Z',
  },
  {
    id: 'tx_6',
    user_id: 'usr_vyno_001',
    account_id: 'fa_4',
    category_id: 'cat_invest_div',
    type: 'income',
    amount: 145.2,
    currency: 'USD',
    description: 'USDC Staking & Treasury Yield Distribution',
    transaction_date: '2026-09-06T08:00:00Z',
  },
  {
    id: 'tx_7',
    user_id: 'usr_vyno_001',
    account_id: 'fa_2',
    category_id: 'cat_lifestyle',
    type: 'expense',
    amount: 320000,
    currency: 'IDR',
    description: 'Espresso Bar & Weekend Coworking Pass',
    transaction_date: '2026-09-07T15:45:00Z',
  },
];

export const mockBudgets: Budget[] = [
  {
    id: 'bg_1',
    user_id: 'usr_vyno_001',
    category_id: 'cat_housing',
    category_name: 'Housing & Living',
    amount: 700,
    spent: 531.25, // IDR converted
    currency: 'USD',
    period: 'monthly',
    start_date: '2026-09-01',
    end_date: '2026-09-30',
  },
  {
    id: 'bg_2',
    user_id: 'usr_vyno_001',
    category_id: 'cat_food',
    category_name: 'Food & Groceries',
    amount: 400,
    spent: 245.0,
    currency: 'USD',
    period: 'monthly',
    start_date: '2026-09-01',
    end_date: '2026-09-30',
  },
  {
    id: 'bg_3',
    user_id: 'usr_vyno_001',
    category_id: 'cat_subscriptions',
    category_name: 'Software & Tools',
    amount: 120,
    spent: 108.5,
    currency: 'USD',
    period: 'monthly',
    start_date: '2026-09-01',
    end_date: '2026-09-30',
  },
  {
    id: 'bg_4',
    user_id: 'usr_vyno_001',
    category_id: 'cat_lifestyle',
    category_name: 'Lifestyle & Fitness',
    amount: 250,
    spent: 130.0,
    currency: 'USD',
    period: 'monthly',
    start_date: '2026-09-01',
    end_date: '2026-09-30',
  },
];

export const mockGoals: FinancialGoal[] = [
  {
    id: 'gl_1',
    user_id: 'usr_vyno_001',
    name: '6-Month Runway Emergency Fund',
    target_amount: 15000,
    current_amount: 11450,
    currency: 'USD',
    deadline: '2026-12-31',
    status: 'active',
    category: 'Safety Net',
  },
  {
    id: 'gl_2',
    user_id: 'usr_vyno_001',
    name: 'Prop Firm Scaling Buffer ($200k Acc)',
    target_amount: 8000,
    current_amount: 5700,
    currency: 'USD',
    deadline: '2026-11-15',
    status: 'active',
    category: 'Trading Capital',
  },
  {
    id: 'gl_3',
    user_id: 'usr_vyno_001',
    name: 'Triple Ultrawide Bloomberg/Trading Rig',
    target_amount: 3200,
    current_amount: 3200,
    currency: 'USD',
    deadline: '2026-08-30',
    status: 'completed',
    category: 'Equipment',
  },
];

export const mockTradingAccounts: TradingAccount[] = [
  {
    id: 'ta_1',
    user_id: 'usr_vyno_001',
    name: 'FTMO $100K Funded',
    broker: 'FTMO EU Server',
    account_type: 'prop',
    currency: 'USD',
    initial_balance: 100000,
    current_balance: 106420,
    is_active: true,
    profit_target: 10000,
    max_drawdown_limit: 10000,
  },
  {
    id: 'ta_2',
    user_id: 'usr_vyno_001',
    name: 'IC Markets Raw ECN',
    broker: 'IC Markets Global',
    account_type: 'broker',
    currency: 'USD',
    initial_balance: 10000,
    current_balance: 13840,
    is_active: true,
  },
  {
    id: 'ta_3',
    user_id: 'usr_vyno_001',
    name: 'Bybit Derivatives Crypto',
    broker: 'Bybit Live',
    account_type: 'personal',
    currency: 'USD',
    initial_balance: 5000,
    current_balance: 6180,
    is_active: true,
  },
];

export const mockStrategies: Strategy[] = [
  {
    id: 'strat_1',
    user_id: 'usr_vyno_001',
    name: 'Liquidity Sweep + MSS',
    description: 'Purge of previous Asian high/low followed by Market Structure Shift on M5.',
    rules: [
      'Look for key liquidity pool grab during London/NY open',
      'Confirm displacement candle with Fair Value Gap',
      'Stop loss placed behind the sweep wick (max 15 pips)',
      'Minimum RR requirement of 1:2.5',
      'Do not trade 15 mins before or after Red Folder News',
    ],
    is_active: true,
    win_rate: 72.7,
    total_trades: 22,
    pnl: 5840,
  },
  {
    id: 'strat_2',
    user_id: 'usr_vyno_001',
    name: 'London Breakout Continuation',
    description: 'Break of pre-market consolidation with strong volume expansion.',
    rules: [
      'Mark 06:00 - 08:00 GMT consolidation box',
      'Enter on retest of breakout level',
      'Target 1.5x ADR or opposing liquidity pool',
    ],
    is_active: true,
    win_rate: 58.3,
    total_trades: 12,
    pnl: 1720,
  },
  {
    id: 'strat_3',
    user_id: 'usr_vyno_001',
    name: 'Asian Range Mean Reversion',
    description: 'Fading extreme deviations from session VWAP during Asian low volatility hours.',
    rules: [
      'Strictly avoid when USD or JPY news scheduled in Tokyo open',
      'Take profit at central VWAP midline',
      'Hard SL of 12 pips',
    ],
    is_active: true,
    win_rate: 50.0,
    total_trades: 8,
    pnl: 340,
  },
  {
    id: 'strat_4',
    user_id: 'usr_vyno_001',
    name: 'Impulsive News Chase (Anti-Pattern)',
    description: 'Jumping into volatile candlesticks immediately after economic data release.',
    rules: ['DO NOT TRADE: Proven negative expectancy setup.'],
    is_active: false,
    win_rate: 20.0,
    total_trades: 5,
    pnl: -1680,
  },
];

export const mockTrades: Trade[] = [
  {
    id: 'tr_1',
    user_id: 'usr_vyno_001',
    trading_account_id: 'ta_1',
    trading_account_name: 'FTMO $100K Funded',
    symbol: 'XAUUSD',
    asset_type: 'commodities',
    direction: 'buy',
    entry_price: 2512.4,
    exit_price: 2530.8,
    stop_loss: 2507.2,
    take_profit: 2531.0,
    position_size: 2.5,
    leverage: 30,
    timeframe: 'M5',
    session: 'London',
    entry_time: '2026-09-07T08:35:00Z',
    exit_time: '2026-09-07T11:42:00Z',
    risk_amount: 400,
    reward_amount: 1415,
    profit_loss: 1415,
    profit_loss_percent: 1.41,
    r_multiple: 3.53,
    commission: 15,
    swap: 0,
    net_profit_loss: 1400,
    status: 'closed',
    entry_reason: 'Asian low swept cleanly at 2510 with 5m bullish divergence and displacement candle.',
    exit_reason: 'Hit TP right at London high liquidity pool.',
    strategy_id: 'strat_1',
    strategy_name: 'Liquidity Sweep + MSS',
    psychology: {
      emotion: 'confident',
      confidence: 9,
      fomo: false,
      revenge_trading: false,
      greed: false,
      fear: false,
      followed_plan: true,
      discipline_score: 10,
      before_trade_note: 'Patiently waited for the 08:30 sweep. Set alert and did not jump early.',
      during_trade_note: 'Position moved into profit swiftly. Trailed SL to breakeven after +1.5R.',
      after_trade_note: 'Flawless execution. Exited at predetermined TP without greeding for more.',
    },
    screenshot_url: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: 'tr_2',
    user_id: 'usr_vyno_001',
    trading_account_id: 'ta_1',
    trading_account_name: 'FTMO $100K Funded',
    symbol: 'EURUSD',
    asset_type: 'forex',
    direction: 'sell',
    entry_price: 1.0885,
    exit_price: 1.0912,
    stop_loss: 1.0910,
    take_profit: 1.082,
    position_size: 3.0,
    leverage: 30,
    timeframe: 'M15',
    session: 'New York',
    entry_time: '2026-09-05T13:42:00Z',
    exit_time: '2026-09-05T14:15:00Z',
    risk_amount: 400,
    reward_amount: 800,
    profit_loss: -405,
    profit_loss_percent: -0.4,
    r_multiple: -1.01,
    commission: 18,
    swap: 0,
    net_profit_loss: -423,
    status: 'closed',
    entry_reason: 'Short after seeing rapid red candle right after US NFP release.',
    exit_reason: 'Whipsaw spike triggered SL.',
    strategy_id: 'strat_4',
    strategy_name: 'Impulsive News Chase (Anti-Pattern)',
    correlated_news: {
      event_name: 'US Non-Farm Payrolls',
      impact: 'high',
      time_diff_minutes: 12,
      currency: 'USD',
    },
    psychology: {
      emotion: 'anxious',
      confidence: 4,
      fomo: true,
      revenge_trading: false,
      greed: true,
      fear: true,
      followed_plan: false,
      discipline_score: 3,
      before_trade_note: 'Thought market was going to dump hard without me. Violated no-news rule.',
      during_trade_note: 'Heart rate spiked. Price whipped 20 pips opposite immediately.',
      after_trade_note: 'Blatant rule break. Never trade within 30m of US NFP. AI alert triggered.',
    },
    screenshot_url: 'https://images.unsplash.com/photo-1642543492481-44e81e3914a7?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: 'tr_3',
    user_id: 'usr_vyno_001',
    trading_account_id: 'ta_2',
    trading_account_name: 'IC Markets Raw ECN',
    symbol: 'GBPUSD',
    asset_type: 'forex',
    direction: 'buy',
    entry_price: 1.3045,
    exit_price: 1.3125,
    stop_loss: 1.3015,
    take_profit: 1.313,
    position_size: 2.0,
    leverage: 50,
    timeframe: 'H1',
    session: 'London',
    entry_time: '2026-09-04T09:15:00Z',
    exit_time: '2026-09-04T16:30:00Z',
    risk_amount: 300,
    reward_amount: 800,
    profit_loss: 800,
    profit_loss_percent: 2.66,
    r_multiple: 2.66,
    commission: 14,
    swap: 3,
    net_profit_loss: 789,
    status: 'closed',
    entry_reason: 'Clean breakout of weekly descending channel on H1 with high bull volume.',
    exit_reason: 'Closed into 1.3125 resistance ahead of NY close.',
    strategy_id: 'strat_2',
    strategy_name: 'London Breakout Continuation',
    psychology: {
      emotion: 'confident',
      confidence: 8,
      fomo: false,
      revenge_trading: false,
      greed: false,
      fear: false,
      followed_plan: true,
      discipline_score: 9,
      before_trade_note: 'Good setup on 1H chart. Risk calculated accurately to 0.75%.',
      during_trade_note: 'Held through small pullback without panic.',
      after_trade_note: 'Disciplined trade, satisfied with adherence to execution rules.',
    },
    screenshot_url: 'https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: 'tr_4',
    user_id: 'usr_vyno_001',
    trading_account_id: 'ta_3',
    trading_account_name: 'Bybit Derivatives Crypto',
    symbol: 'BTCUSD',
    asset_type: 'crypto',
    direction: 'buy',
    entry_price: 63200,
    exit_price: 64850,
    stop_loss: 62400,
    take_profit: 65000,
    position_size: 0.8,
    leverage: 10,
    timeframe: 'H4',
    session: 'Overlap',
    entry_time: '2026-09-02T19:00:00Z',
    exit_time: '2026-09-03T22:10:00Z',
    risk_amount: 320,
    reward_amount: 660,
    profit_loss: 660,
    profit_loss_percent: 2.06,
    r_multiple: 2.06,
    commission: 22,
    swap: -8,
    net_profit_loss: 630,
    status: 'closed',
    entry_reason: '4H order block retest after reclaiming $63,000 psychological level.',
    exit_reason: 'Manually took profit as momentum stalled under $65k.',
    strategy_id: 'strat_1',
    strategy_name: 'Liquidity Sweep + MSS',
    psychology: {
      emotion: 'neutral',
      confidence: 7,
      fomo: false,
      revenge_trading: false,
      greed: false,
      fear: false,
      followed_plan: true,
      discipline_score: 8,
      before_trade_note: 'Calm mindset. Kept leverage conservative (10x).',
      during_trade_note: 'Let the trade play out over 24 hours without constant chart watching.',
      after_trade_note: 'Solid swing trade execution.',
    },
  },
  {
    id: 'tr_5',
    user_id: 'usr_vyno_001',
    trading_account_id: 'ta_1',
    trading_account_name: 'FTMO $100K Funded',
    symbol: 'USDJPY',
    asset_type: 'forex',
    direction: 'buy',
    entry_price: 145.2,
    exit_price: 144.8,
    stop_loss: 144.8,
    take_profit: 146.0,
    position_size: 2.0,
    leverage: 30,
    timeframe: 'M5',
    session: 'Asian',
    entry_time: '2026-09-01T02:15:00Z',
    exit_time: '2026-09-01T03:30:00Z',
    risk_amount: 350,
    reward_amount: 700,
    profit_loss: -350,
    profit_loss_percent: -0.35,
    r_multiple: -1.0,
    commission: 12,
    swap: 0,
    net_profit_loss: -362,
    status: 'closed',
    entry_reason: 'Tried to catch falling knife reversal after BOJ governor remark.',
    exit_reason: 'Hit strict Stop Loss.',
    strategy_id: 'strat_3',
    strategy_name: 'Asian Range Mean Reversion',
    correlated_news: {
      event_name: 'BOJ Governor Speech',
      impact: 'high',
      time_diff_minutes: 25,
      currency: 'JPY',
    },
    psychology: {
      emotion: 'fearful',
      confidence: 5,
      fomo: false,
      revenge_trading: true,
      greed: false,
      fear: true,
      followed_plan: false,
      discipline_score: 5,
      before_trade_note: 'Felt irritated from an earlier missed move. Revenge instinct was lurking.',
      during_trade_note: 'Hesitant. Should not have fought the trend during Asian session.',
      after_trade_note: 'Good thing SL was placed and not moved. Loss respected.',
    },
  },
  {
    id: 'tr_6',
    user_id: 'usr_vyno_001',
    trading_account_id: 'ta_1',
    trading_account_name: 'FTMO $100K Funded',
    symbol: 'XAUUSD',
    asset_type: 'commodities',
    direction: 'sell',
    entry_price: 2528.0,
    exit_price: 2505.0,
    stop_loss: 2533.0,
    take_profit: 2505.0,
    position_size: 2.0,
    leverage: 30,
    timeframe: 'M15',
    session: 'New York',
    entry_time: '2026-08-28T14:45:00Z',
    exit_time: '2026-08-28T18:12:00Z',
    risk_amount: 500,
    reward_amount: 2300,
    profit_loss: 2300,
    profit_loss_percent: 2.3,
    r_multiple: 4.6,
    commission: 16,
    swap: 0,
    net_profit_loss: 2284,
    status: 'closed',
    entry_reason: 'Massive buy-side liquidity sweep at Asian & London highs, followed by NY reversal.',
    exit_reason: 'Full take profit target reached at daily pivot support.',
    strategy_id: 'strat_1',
    strategy_name: 'Liquidity Sweep + MSS',
    psychology: {
      emotion: 'confident',
      confidence: 10,
      fomo: false,
      revenge_trading: false,
      greed: false,
      fear: false,
      followed_plan: true,
      discipline_score: 10,
      before_trade_note: 'Textbook setup. Waited for 15m candle close below the sweep level.',
      during_trade_note: 'No emotional interference. Let winners run completely.',
      after_trade_note: 'Best trade of the month (+4.6R). System executed to perfection.',
    },
  },
];

export const mockMarketEvents: MarketEvent[] = [
  // --- September 2026 ---
  {
    id: 'me_6',
    event_name: 'BOJ Monetary Policy Statement',
    currency: 'JPY',
    country: 'Japan',
    event_time: '2026-09-01T03:00:00Z',
    impact: 'high',
    previous: '0.25%',
    forecast: '0.25%',
    actual: '0.25%',
    source: 'Bank of Japan',
  },
  {
    id: 'me_5',
    event_name: 'US Non-Farm Payrolls',
    currency: 'USD',
    country: 'United States',
    event_time: '2026-09-05T12:30:00Z',
    impact: 'high',
    previous: '114K',
    forecast: '161K',
    actual: '142K',
    source: 'US Dept of Labor',
  },
  {
    id: 'me_1',
    event_name: 'US Core CPI m/m',
    currency: 'USD',
    country: 'United States',
    event_time: '2026-09-09T12:30:00Z',
    impact: 'high',
    previous: '0.2%',
    forecast: '0.2%',
    actual: undefined,
    source: 'Bureau of Labor Statistics',
  },
  {
    id: 'me_4',
    event_name: 'UK Claimant Count Change',
    currency: 'GBP',
    country: 'United Kingdom',
    event_time: '2026-09-10T06:00:00Z',
    impact: 'medium',
    previous: '135.0K',
    forecast: '95.5K',
    actual: undefined,
    source: 'Office for National Statistics',
  },
  {
    id: 'me_2',
    event_name: 'ECB Main Refinancing Rate',
    currency: 'EUR',
    country: 'Euro Zone',
    event_time: '2026-09-10T12:15:00Z',
    impact: 'high',
    previous: '3.75%',
    forecast: '3.50%',
    actual: undefined,
    source: 'European Central Bank',
  },
  {
    id: 'me_3',
    event_name: 'US PPI m/m',
    currency: 'USD',
    country: 'United States',
    event_time: '2026-09-11T12:30:00Z',
    impact: 'medium',
    previous: '0.1%',
    forecast: '0.2%',
    actual: undefined,
    source: 'Bureau of Labor Statistics',
  },
  {
    id: 'me_7',
    event_name: 'US Core Retail Sales m/m',
    currency: 'USD',
    country: 'United States',
    event_time: '2026-09-15T12:30:00Z',
    impact: 'high',
    previous: '0.4%',
    forecast: '0.2%',
    actual: undefined,
    source: 'US Census Bureau',
  },
  {
    id: 'me_8',
    event_name: 'UK CPI y/y',
    currency: 'GBP',
    country: 'United Kingdom',
    event_time: '2026-09-16T06:00:00Z',
    impact: 'high',
    previous: '2.2%',
    forecast: '2.2%',
    actual: undefined,
    source: 'Office for National Statistics',
  },
  {
    id: 'me_9',
    event_name: 'FOMC Economic Projections & Statement',
    currency: 'USD',
    country: 'United States',
    event_time: '2026-09-16T18:00:00Z',
    impact: 'high',
    previous: '5.50%',
    forecast: '5.25%',
    actual: undefined,
    source: 'Federal Reserve',
  },
  {
    id: 'me_10',
    event_name: 'FOMC Press Conference - Jerome Powell',
    currency: 'USD',
    country: 'United States',
    event_time: '2026-09-16T18:30:00Z',
    impact: 'high',
    previous: undefined,
    forecast: undefined,
    actual: undefined,
    source: 'Federal Reserve',
  },
  {
    id: 'me_11',
    event_name: 'BOE Official Bank Rate',
    currency: 'GBP',
    country: 'United Kingdom',
    event_time: '2026-09-17T11:00:00Z',
    impact: 'high',
    previous: '5.00%',
    forecast: '5.00%',
    actual: undefined,
    source: 'Bank of England',
  },
  {
    id: 'me_12',
    event_name: 'BOJ Policy Rate Decision',
    currency: 'JPY',
    country: 'Japan',
    event_time: '2026-09-18T03:30:00Z',
    impact: 'high',
    previous: '0.25%',
    forecast: '0.25%',
    actual: undefined,
    source: 'Bank of Japan',
  },
  {
    id: 'me_13',
    event_name: 'Eurozone Flash Manufacturing & Services PMI',
    currency: 'EUR',
    country: 'Euro Zone',
    event_time: '2026-09-23T08:00:00Z',
    impact: 'high',
    previous: '51.0',
    forecast: '50.6',
    actual: undefined,
    source: 'S&P Global',
  },
  {
    id: 'me_14',
    event_name: 'SNB Monetary Policy Assessment & Rate',
    currency: 'CHF',
    country: 'Switzerland',
    event_time: '2026-09-24T07:30:00Z',
    impact: 'high',
    previous: '1.25%',
    forecast: '1.00%',
    actual: undefined,
    source: 'Swiss National Bank',
  },
  {
    id: 'me_15',
    event_name: 'US Core PCE Price Index m/m',
    currency: 'USD',
    country: 'United States',
    event_time: '2026-09-25T12:30:00Z',
    impact: 'high',
    previous: '0.2%',
    forecast: '0.2%',
    actual: undefined,
    source: 'Bureau of Economic Analysis',
  },
  {
    id: 'me_16',
    event_name: 'US Final GDP q/q',
    currency: 'USD',
    country: 'United States',
    event_time: '2026-09-30T12:30:00Z',
    impact: 'high',
    previous: '3.0%',
    forecast: '3.0%',
    actual: undefined,
    source: 'Bureau of Economic Analysis',
  },

  // --- October 2026 ---
  {
    id: 'me_17',
    event_name: 'US ISM Manufacturing PMI',
    currency: 'USD',
    country: 'United States',
    event_time: '2026-10-01T14:00:00Z',
    impact: 'high',
    previous: '47.2',
    forecast: '47.5',
    actual: undefined,
    source: 'Institute for Supply Management',
  },
  {
    id: 'me_18',
    event_name: 'US Non-Farm Payrolls & Unemployment Rate',
    currency: 'USD',
    country: 'United States',
    event_time: '2026-10-02T12:30:00Z',
    impact: 'high',
    previous: '142K',
    forecast: '150K',
    actual: undefined,
    source: 'US Dept of Labor',
  },
  {
    id: 'me_19',
    event_name: 'RBA Cash Rate Decision & Statement',
    currency: 'AUD',
    country: 'Australia',
    event_time: '2026-10-06T03:30:00Z',
    impact: 'high',
    previous: '4.35%',
    forecast: '4.35%',
    actual: undefined,
    source: 'Reserve Bank of Australia',
  },
  {
    id: 'me_20',
    event_name: 'US Core CPI m/m & CPI y/y',
    currency: 'USD',
    country: 'United States',
    event_time: '2026-10-08T12:30:00Z',
    impact: 'high',
    previous: '0.2%',
    forecast: '0.2%',
    actual: undefined,
    source: 'Bureau of Labor Statistics',
  },
  {
    id: 'me_21',
    event_name: 'US Retail Sales m/m',
    currency: 'USD',
    country: 'United States',
    event_time: '2026-10-15T12:30:00Z',
    impact: 'high',
    previous: '0.1%',
    forecast: '0.3%',
    actual: undefined,
    source: 'US Census Bureau',
  },
  {
    id: 'me_22',
    event_name: 'BOC Overnight Rate & Monetary Policy',
    currency: 'CAD',
    country: 'Canada',
    event_time: '2026-10-21T13:45:00Z',
    impact: 'high',
    previous: '4.25%',
    forecast: '3.75%',
    actual: undefined,
    source: 'Bank of Canada',
  },
  {
    id: 'me_23',
    event_name: 'ECB Monetary Policy Statement & Press Conference',
    currency: 'EUR',
    country: 'Euro Zone',
    event_time: '2026-10-29T12:15:00Z',
    impact: 'high',
    previous: '3.50%',
    forecast: '3.25%',
    actual: undefined,
    source: 'European Central Bank',
  },
  {
    id: 'me_24',
    event_name: 'US Core PCE Price Index m/m',
    currency: 'USD',
    country: 'United States',
    event_time: '2026-10-30T12:30:00Z',
    impact: 'high',
    previous: '0.2%',
    forecast: '0.2%',
    actual: undefined,
    source: 'Bureau of Economic Analysis',
  },
  {
    id: 'me_25',
    event_name: 'BOJ Outlook Report & Policy Rate',
    currency: 'JPY',
    country: 'Japan',
    event_time: '2026-10-30T03:00:00Z',
    impact: 'high',
    previous: '0.25%',
    forecast: '0.25%',
    actual: undefined,
    source: 'Bank of Japan',
  },

  // --- November 2026 ---
  {
    id: 'me_26',
    event_name: 'US FOMC Statement & Federal Funds Rate',
    currency: 'USD',
    country: 'United States',
    event_time: '2026-11-04T19:00:00Z',
    impact: 'high',
    previous: '5.25%',
    forecast: '5.00%',
    actual: undefined,
    source: 'Federal Reserve',
  },
  {
    id: 'me_27',
    event_name: 'BOE Monetary Policy Report & Rate',
    currency: 'GBP',
    country: 'United Kingdom',
    event_time: '2026-11-05T12:00:00Z',
    impact: 'high',
    previous: '5.00%',
    forecast: '4.75%',
    actual: undefined,
    source: 'Bank of England',
  },
  {
    id: 'me_28',
    event_name: 'US Non-Farm Payrolls (NFP)',
    currency: 'USD',
    country: 'United States',
    event_time: '2026-11-06T13:30:00Z',
    impact: 'high',
    previous: '150K',
    forecast: '155K',
    actual: undefined,
    source: 'US Dept of Labor',
  },
  {
    id: 'me_29',
    event_name: 'US CPI m/m & Core CPI y/y',
    currency: 'USD',
    country: 'United States',
    event_time: '2026-11-12T13:30:00Z',
    impact: 'high',
    previous: '0.2%',
    forecast: '0.2%',
    actual: undefined,
    source: 'Bureau of Labor Statistics',
  },
  {
    id: 'me_30',
    event_name: 'US Preliminary GDP q/q',
    currency: 'USD',
    country: 'United States',
    event_time: '2026-11-25T13:30:00Z',
    impact: 'high',
    previous: '2.8%',
    forecast: '2.8%',
    actual: undefined,
    source: 'Bureau of Economic Analysis',
  },
];

export const mockAIInsights: AIInsight[] = [
  {
    id: 'ins_1',
    user_id: 'usr_vyno_001',
    insight_type: 'psychology',
    title: 'High-Impact News Trading Vulnerability',
    content:
      'Pola terdeteksi: 2 dari 6 trade terakhir dieksekusi kurang dari 25 menit di sekitar High-Impact News (US NFP & BOJ). Kedua trade tersebut berujung kerugian dengan skor disiplin rata-rata 4.0. Sebaliknya, trade tanpa news memiliki Win Rate 100% dan average R:R 3.4R. Rekomendasi: Pasang aturan "30-min News Lockout" untuk melindungi akun prop firm Anda.',
    source_period: 'Last 14 Days',
    created_at: '2026-09-07T18:00:00Z',
    severity: 'warning',
  },
  {
    id: 'ins_2',
    user_id: 'usr_vyno_001',
    insight_type: 'trading',
    title: 'Strategy Alpha: Liquidity Sweep + MSS',
    content:
      'Setup "Liquidity Sweep + MSS" menghasilkan profit bersih +$3,684 dengan Win Rate 75% di sesi London & NY. Rata-rata R multiple mencapai 3.39R. Ini adalah keunggulan (edge) utama Anda bulan ini. Pertahankan fokus hanya pada pair XAUUSD & GBPUSD untuk setup ini.',
    source_period: 'Current Month',
    created_at: '2026-09-06T12:00:00Z',
    severity: 'success',
  },
  {
    id: 'ins_3',
    user_id: 'usr_vyno_001',
    insight_type: 'financial',
    title: 'Cash Flow & Runway Acceleration',
    content:
      'Penyaluran profit split FTMO ($2,850) meningkatkan runway safety net Anda menjadi 76% dari target $15,000. Pengeluaran kategori Software/Subscriptions mendekati batas budget (90.4%). Namun arus kas bersih bulan ini surplus +$4,120 USD.',
    source_period: 'September 2026',
    created_at: '2026-09-05T09:30:00Z',
    severity: 'info',
  },
];
